/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tte;    //Imports
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.sqlite.JDBC;

/*
 * @author Surya
 */
public class Selecttrain extends javax.swing.JFrame {

    /**
     * Creates new form Selecttrain
     */
    public Selecttrain() {  //Constructor
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 204, 153));
        Connect();
    }
    
    Connection con; //Database connection variables
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect()   //Method to connect to the database
    {
        try {
            Class.forName("org.sqlite.JDBC");
            con= DriverManager.getConnection("jdbc:sqlite::resource:onlinette.db");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Passengerdetails1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Error");
        } catch (SQLException ex) {
            Logger.getLogger(Passengerdetails1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Error");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txttrainno = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txttrainname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcoach = new javax.swing.JComboBox<>();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Train no");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Select date");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txttrainno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txttrainno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select train", "16127", "12631", "12633", "16723" }));
        txttrainno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrainnoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Train name");

        txttrainname.setEditable(false);
        txttrainname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txttrainname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrainnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Coach");

        txtcoach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcoach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcoachActionPerformed(evt);
            }
        });

        txtdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtdate.setMinSelectableDate(new Date());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttrainno, 0, 329, Short.MAX_VALUE)
                            .addComponent(txttrainname)
                            .addComponent(txtcoach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txttrainno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txttrainname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcoach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Welcome Select train details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String trainno= txttrainno.getSelectedItem().toString();    //Getting the user inputs
        String coach= txtcoach.getSelectedItem().toString();
        Date date= txtdate.getDate();
        
        SimpleDateFormat format1 = new SimpleDateFormat("dd-MM-yyyy");  //Appropriate date format
        String newdate = format1.format(date).toString(); 
        Date date1= txtdate.getDate();
        Passengerdetails1 p= new Passengerdetails1();
        this.hide();
        p.txttrainno1.setText(trainno); //Setting the user inputs onto the passengerdetails form
        p.txtdate1.setText(newdate);
        p.txtcoachno1.setText(coach);
        p.txtdate2.setDate(date1);
        p.txtdate2.hide();
        p.jLabel6.setVisible(false);
        try {   //Geting the travelling passenger details from the passengerdetails table and setting it onto the JTable
            pst=con.prepareStatement("select Seatno,Name,Source,Destination,ID,Phoneno,Status from passengerdetails;");
            rs=pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c=rsd.getColumnCount();
            
            DefaultTableModel d= (DefaultTableModel)p.bookingtable.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v=new Vector();
                for(int i=0;i<c;i++)
                {
                    v.add(rs.getString("Seatno"));
                    v.add(rs.getString("Name"));
                    v.add(rs.getString("Source"));
                    v.add(rs.getString("Destination"));
                    v.add(rs.getString("ID"));
                    v.add(rs.getString("Phoneno"));
                    v.add(rs.getString("Status"));
       
                }
                d.addRow(v);
            }
                p.setVisible(true);
                p.changeTable(p.bookingtable, 6);
        } catch (SQLException ex) {
            Logger.getLogger(Passengerdetails1.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Error");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login l= new Login(); //Displaying login form
        this.hide();
        l.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txttrainnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttrainnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txttrainnameActionPerformed

    private void txttrainnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttrainnoActionPerformed
        // TODO add your handling code here:
        String trainno = txttrainno.getSelectedItem().toString(); //Getting the train number input
        if(trainno.equals(""))  //Auto filling the train name
            txttrainname.setText("");
        if(trainno.equals("16127"))
        {
            txtcoach.removeAllItems();
            txttrainname.setText("Chennai Egmore - Guruvayur Express");   
        }
        if(trainno.equals("12631"))
        {
            txtcoach.removeAllItems();
            txttrainname.setText("Chennai Egmore - Tirunelveli Nellai SF Express");
        }
        if(trainno.equals("12633"))
        {
            txtcoach.removeAllItems();
            txttrainname.setText("Chennai Egmore - Kanniyakumari SF Express");
        }
        if(trainno.equals("16723"))
        {
            txtcoach.removeAllItems();
            txttrainname.setText("Chennai Egmore - Kollam Ananthapuri Express");
        }
        
        
        try {   //Adding the train coaches to the drop down using data from the traincoaches table in the database
            pst=con.prepareStatement("select coach from traincoaches where trainno = ?;");
            pst.setString(1,trainno);
            rs=pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            int c;
            c=rsd.getColumnCount();
            
            txtcoach.addItem("");
            
            while(rs.next())
            {
                for(int i=0;i<c;i++)
                {
                    txtcoach.addItem(rs.getString("coach"));
                }
            }
        }catch (SQLException ex) {
            Logger.getLogger(Selecttrain.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Error");
        }
                    
    }//GEN-LAST:event_txttrainnoActionPerformed

    private void txtcoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcoachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcoachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selecttrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selecttrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selecttrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selecttrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selecttrain().setVisible(true); //Showing the form
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> txtcoach;
    public com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txttrainname;
    public static javax.swing.JComboBox<String> txttrainno;
    // End of variables declaration//GEN-END:variables
}
